### PR TITLE
automate builds on launchpad

### PR DESCRIPTION
**Pull request by thopiekar**
It should fix automated builds on launchpad.

---

https://code.launchpad.net/~thopiekar/+recipe/systemd+kdbus

### CODE REVIEW

**Comment by albfan** [comment]
Why disable test and ignore changed/added symbols? I have seen that changes on your launchpad repo, but don't know why it is needed, instead of fixed. systemd is a key feature so I prefer to test it.

Those test must be there for any reason, although is true I bypassed it on:
- 6ae152c5a9f54e1bda583e113771c229e7a0ef92
- 6b7d81169f369dd445691b2dee3864a2148b4648
- 93a1538e9c34190daa000e7c0c45e3a10a4ec303 (this is a correction not a bypass)

**Comment by thopiekar** [comment]
Well, I already got 2 times feedback by the launchpad Admins that I should consider skipping doing tests on my private builds. Doing tests often takes much time and launchpad as a free service likes save CPU useage as much es possible.

But as we won't do many builds (not truely daily) I would revert this commit if you like.

Now about ignoring changed/added symbols. Well, debhelper has a tool which looks for changed/added/removed symbols and there are different ways to handle that. At the moment builds will fail on changes `-c4`, but using my changes `-c0` it generates a new list, warns about it, but does not fail when finding differences.

As you can see in this build log ( https://launchpadlibrarian.net/203009918/buildlog_ubuntu-vivid-amd64.systemd_219-9ubuntu10~rev10~201504121752~ubuntu15.04.1_BUILDING.txt.gz ) there are many differences (shown in the known diff format).

PS: The version `219-9ubuntu10~rev10~201504121752~ubuntu15.04.1
`, which is the package version I use here, appears in every new line. As I always skipped this by `-c0` in the past, I never read how to resolve this in a "clean" way, e.g. replace on those lines `219-9ubuntu10~rev10~201504121752~ubuntu15.04.1` simply with `219`.

**Comment by albfan** [comment]
Reading

http://manpages.ubuntu.com/manpages/hardy/man1/dpkg-gensymbols.1.html

I guess `-c1` (or remove -c) is a sane change (as it won't break compatibility)

Anyway it would be great to solve symbols issue following

http://stackoverflow.com/a/12674910/848072

Don't know exact steps to fix it.

It's ok to bypass or fix test, but I refuse to bypass symbol checks. 

Do you know the steps to reproduce launchpad compilation? This repo README guide is hacky, but produce .deb package correctly.

**Comment by thopiekar** [comment]
As far as I know doing builds using `pbuilder` is very similar to launchpad's buildssystem. I'll try to fix that problem with the symbols when I find the time for that

**Comment by thopiekar** [comment]
Ok, all needed changes have been made. Builds passes.
- https://code.launchpad.net/~thopiekar/+recipe/systemd+kdbus

However, #2 should be now more important.

**Comment by albfan** [comment]
I have merge all this changes with new upstream repo. Now it's time to propose those changes to actual maintainers. Let's see what they have to say.

**Pull request closed without merging**
